-- H2 2.1.214;
;             
CREATE USER IF NOT EXISTS "SA" SALT 'fe601ad7b51c979d' HASH '1d0fa2453783e9b613bb76fbc9f85560091bea1adaeda35c38708b6b3a880bf8' ADMIN;         
CREATE SEQUENCE "PUBLIC"."medical_record_seq" START WITH 1 RESTART WITH 101 INCREMENT BY 50;  
CREATE MEMORY TABLE "PUBLIC"."fire_station"(
    "station" INTEGER NOT NULL,
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 14) DEFAULT ON NULL NOT NULL,
    "address" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."fire_station" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("id"); 
-- 13 +/- SELECT COUNT(*) FROM PUBLIC.fire_station;           
INSERT INTO "PUBLIC"."fire_station" VALUES
(3, 1, '1509 Culver St'),
(2, 2, '29 15th St'),
(3, 3, '834 Binoc Ave'),
(1, 4, '644 Gershwin Cir'),
(3, 5, '748 Townings Dr'),
(3, 6, '112 Steppes Pl'),
(4, 7, '489 Manchester St'),
(2, 8, '892 Downing Ct'),
(1, 9, '908 73rd St'),
(4, 10, '112 Steppes Pl'),
(1, 11, '947 E. Rose Dr'),
(3, 12, '748 Townings Dr'),
(2, 13, '951 LoneTree Rd'); 
CREATE MEMORY TABLE "PUBLIC"."medical_record"(
    "birthdate" DATE,
    "id" BIGINT NOT NULL,
    "first_name" CHARACTER VARYING(255),
    "last_name" CHARACTER VARYING(255),
    "allergies" CHARACTER VARYING(255) ARRAY,
    "medications" CHARACTER VARYING(255) ARRAY
);        
ALTER TABLE "PUBLIC"."medical_record" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("id");               
-- 23 +/- SELECT COUNT(*) FROM PUBLIC.medical_record;         
INSERT INTO "PUBLIC"."medical_record" VALUES
(DATE '1984-03-06', 1, 'John', 'Boyd', ARRAY ['nillacilan'], ARRAY ['aznol:350mg', 'hydrapermazol:100mg']),
(DATE '1989-03-06', 2, 'Jacob', 'Boyd', ARRAY [], ARRAY ['pharmacol:5000mg', 'terazine:10mg', 'noznazol:250mg']),
(DATE '2012-02-18', 3, 'Tenley', 'Boyd', ARRAY ['peanut'], ARRAY []),
(DATE '2017-09-06', 4, 'Roger', 'Boyd', ARRAY [], ARRAY []),
(DATE '1986-01-08', 5, 'Felicia', 'Boyd', ARRAY ['xilliathal'], ARRAY ['tetracyclaz:650mg']),
(DATE '1989-01-03', 6, 'Jonanathan', 'Marrack', ARRAY [], ARRAY []),
(DATE '2012-02-18', 7, 'Tessa', 'Carman', ARRAY [], ARRAY []),
(DATE '2000-09-06', 8, 'Peter', 'Duncan', ARRAY ['shellfish'], ARRAY []),
(DATE '1980-01-08', 9, 'Foster', 'Shepard', ARRAY [], ARRAY []),
(DATE '1994-03-06', 10, 'Tony', 'Cooper', ARRAY ['shellfish'], ARRAY ['hydrapermazol:300mg', 'dodoxadin:30mg']),
(DATE '1994-03-06', 11, 'Lily', 'Cooper', ARRAY [], ARRAY []),
(DATE '1988-03-06', 12, 'Sophia', 'Zemicks', ARRAY ['peanut', 'shellfish', 'aznol'], ARRAY ['aznol:60mg', 'hydrapermazol:900mg', 'pharmacol:5000mg', 'terazine:500mg']),
(DATE '1985-03-06', 13, 'Warren', 'Zemicks', ARRAY [], ARRAY []),
(DATE '2017-03-06', 14, 'Zach', 'Zemicks', ARRAY [], ARRAY []),
(DATE '1979-08-30', 15, 'Reginold', 'Walker', ARRAY ['illisoxian'], ARRAY ['thradox:700mg']),
(DATE '1982-03-06', 16, 'Jamie', 'Peters', ARRAY [], ARRAY []),
(DATE '1965-04-06', 17, 'Ron', 'Peters', ARRAY [], ARRAY []),
(DATE '1965-03-15', 18, 'Allison', 'Boyd', ARRAY ['nillacilan'], ARRAY ['aznol:200mg']),
(DATE '1975-12-06', 19, 'Brian', 'Stelzer', ARRAY ['nillacilan'], ARRAY ['ibupurin:200mg', 'hydrapermazol:400mg']),
(DATE '1980-07-08', 20, 'Shawna', 'Stelzer', ARRAY [], ARRAY []),
(DATE '2014-03-06', 21, 'Kendrik', 'Stelzer', ARRAY [], ARRAY ['noxidian:100mg', 'pharmacol:2500mg']),
(DATE '1994-03-06', 22, 'Clive', 'Ferguson', ARRAY [], ARRAY []),
(DATE '1945-08-06', 23, 'Eric', 'Cadigan', ARRAY [], ARRAY ['tradoxidine:400mg']);           
CREATE MEMORY TABLE "PUBLIC"."person"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 24) DEFAULT ON NULL NOT NULL,
    "address" CHARACTER VARYING(255),
    "city" CHARACTER VARYING(255),
    "email" CHARACTER VARYING(255),
    "first_name" CHARACTER VARYING(255),
    "last_name" CHARACTER VARYING(255),
    "phone" CHARACTER VARYING(255),
    "zip" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."person" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("id");       
-- 23 +/- SELECT COUNT(*) FROM PUBLIC.person; 
INSERT INTO "PUBLIC"."person" VALUES
(1, '1509 Culver St', 'Culver', 'jaboyd@email.com', 'John', 'Boyd', '841-874-6512', '97451'),
(2, '1509 Culver St', 'Culver', 'drk@email.com', 'Jacob', 'Boyd', '841-874-6513', '97451'),
(3, '1509 Culver St', 'Culver', 'tenz@email.com', 'Tenley', 'Boyd', '841-874-6512', '97451'),
(4, '1509 Culver St', 'Culver', 'jaboyd@email.com', 'Roger', 'Boyd', '841-874-6512', '97451'),
(5, '1509 Culver St', 'Culver', 'jaboyd@email.com', 'Felicia', 'Boyd', '841-874-6544', '97451'),
(6, '29 15th St', 'Culver', 'drk@email.com', 'Jonanathan', 'Marrack', '841-874-6513', '97451'),
(7, '834 Binoc Ave', 'Culver', 'tenz@email.com', 'Tessa', 'Carman', '841-874-6512', '97451'),
(8, '644 Gershwin Cir', 'Culver', 'jaboyd@email.com', 'Peter', 'Duncan', '841-874-6512', '97451'),
(9, '748 Townings Dr', 'Culver', 'jaboyd@email.com', 'Foster', 'Shepard', '841-874-6544', '97451'),
(10, '112 Steppes Pl', 'Culver', 'tcoop@ymail.com', 'Tony', 'Cooper', '841-874-6874', '97451'),
(11, '489 Manchester St', 'Culver', 'lily@email.com', 'Lily', 'Cooper', '841-874-9845', '97451'),
(12, '892 Downing Ct', 'Culver', 'soph@email.com', 'Sophia', 'Zemicks', '841-874-7878', '97451'),
(13, '892 Downing Ct', 'Culver', 'ward@email.com', 'Warren', 'Zemicks', '841-874-7512', '97451'),
(14, '892 Downing Ct', 'Culver', 'zarc@email.com', 'Zach', 'Zemicks', '841-874-7512', '97451'),
(15, '908 73rd St', 'Culver', 'reg@email.com', 'Reginold', 'Walker', '841-874-8547', '97451'),
(16, '908 73rd St', 'Culver', 'jpeter@email.com', 'Jamie', 'Peters', '841-874-7462', '97451'),
(17, '112 Steppes Pl', 'Culver', 'jpeter@email.com', 'Ron', 'Peters', '841-874-8888', '97451'),
(18, '112 Steppes Pl', 'Culver', 'aly@imail.com', 'Allison', 'Boyd', '841-874-9888', '97451'),
(19, '947 E. Rose Dr', 'Culver', 'bstel@email.com', 'Brian', 'Stelzer', '841-874-7784', '97451'),
(20, '947 E. Rose Dr', 'Culver', 'ssanw@email.com', 'Shawna', 'Stelzer', '841-874-7784', '97451'),
(21, '947 E. Rose Dr', 'Culver', 'bstel@email.com', 'Kendrik', 'Stelzer', '841-874-7784', '97451'),
(22, '748 Townings Dr', 'Culver', 'clivfd@ymail.com', 'Clive', 'Ferguson', '841-874-6741', '97451'),
(23, '951 LoneTree Rd', 'Culver', 'gramps@email.com', 'Eric', 'Cadigan', '841-874-7458', '97451');  
